### PR TITLE
Fix for sending timer metrics

### LINKED ISSUE #1: Invalid timer entries being sent downstream
When sending metrics downstream. Timer metrics are sent like so (dumpMessages=true output from statsd):

24 Mar 21:17:24 - Gossiping about timer: 'function1.runtime':1089,1089,1111,1111,1153,1153,1217,1217,1239,1239,1239,1239,1239,1239,1281,1281,1324,1324,1473,1473|ms'

This is obviously malformed and is processed by downstream statsd as NaN. Output of echo timers | nc localhost 8126 (on downstream statsd)

'function1.runtime': [ NaN ],

### PR DESCRIPTION
**Pull request by viralshah**
There is no way to 'aggregate' timer values before sending them
downstream. Fixes #1

### CODE REVIEW

**Comment by jlutzhbo** [comment]
@viralshah Can we merge this please? Thanks!

**Comment by viralshah** [comment]
sure.

**Comment by hjhart** [comment]
Jeez, not sure how this fell off the radar for so long. 

I don't have time to merge this in right now, but I'll try to get to it sometime next week. 👍

**Comment by fguillen** [comment]
Please merge.. 👍

**Comment by hjhart** [comment]
Sorry about the delay folks.

**Pull request merged**
